# Generated by Django 4.1.7 on 2023-07-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lecture_code", models.CharField(max_length=5)),
                ("lecturer_name", models.CharField(max_length=100)),
                ("exam_date", models.DateField()),
                (
                    "exam_period",
                    models.CharField(
                        choices=[("AM", "Morning"), ("PM", "Afternoon")], max_length=5
                    ),
                ),
                ("exam_hall", models.CharField(max_length=50)),
                ("exam_supervisor_code", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept_code", models.CharField(blank=True, max_length=5, null=True)),
                ("dept_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hall_name", models.CharField(max_length=50)),
                ("hall_capacity", models.IntegerField()),
                (
                    "hall_type",
                    models.CharField(
                        choices=[("SM", "Small"), ("MD", "Medium"), ("LG", "Large")],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lecturer_name", models.CharField(max_length=50)),
                ("lecturer_code", models.IntegerField()),
                (
                    "lecturer_level",
                    models.CharField(
                        choices=[
                            ("Assisstant", "Assisstant Lecturers"),
                            ("Lecturer 1", "Lecturer 1"),
                            ("Lecturer 2", "Lecturer 2"),
                            ("Lecturer 3", "Lecturer 3"),
                            ("Senior", "Senior Lecturer"),
                            ("principal", "Principal Lecturer"),
                            ("Chief", "Chief Lecturer"),
                            ("HOD", "Head of Department"),
                        ],
                        max_length=20,
                    ),
                ),
                ("invigilation_type", models.CharField(max_length=20)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("CBE", "Computer Based Exam"),
                            ("PBE", "Written Exam"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lecture_code", models.CharField(max_length=5)),
                ("lecturer_name", models.CharField(max_length=100)),
                ("exam_date", models.DateField()),
                (
                    "exam_period",
                    models.CharField(
                        choices=[("AM", "Morning"), ("PM", "Afternoon")], max_length=5
                    ),
                ),
                ("exam_hall", models.CharField(max_length=50)),
                ("exam_supervisor_code", models.CharField(max_length=5)),
            ],
        ),
    ]
