# Generated by Django 4.1.7 on 2023-07-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invigilation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="invigilation_type",
            field=models.CharField(
                choices=[("SUPER", "Supervisor"), ("INVIGILATOR", "Invigilator")],
                max_length=20,
            ),
        ),
    ]
