# Generated by Django 4.1.7 on 2023-07-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invigilation", "0002_alter_lecturer_invigilation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="lecturer_code",
            field=models.CharField(max_length=10),
        ),
    ]
