# Generated by Django 4.1.7 on 2023-07-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invigilation", "0003_alter_lecturer_lecturer_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="exam_type",
            field=models.CharField(
                choices=[("CBE", "Computer Based Exam"), ("PBE", "Written Exam")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="lecturer_level",
            field=models.CharField(
                choices=[
                    ("Assisstant", "Assisstant Lecturers"),
                    ("Lecturer 1", "Lecturer 1"),
                    ("Lecturer 2", "Lecturer 2"),
                    ("Lecturer 3", "Lecturer 3"),
                    ("Senior", "Senior Lecturer"),
                    ("principal", "Principal Lecturer"),
                    ("Chief", "Chief Lecturer"),
                    ("HOD", "Head of Department"),
                ],
                max_length=50,
            ),
        ),
    ]
