# Generated by Django 4.1.7 on 2023-07-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invigilation", "0004_alter_lecturer_exam_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="lecturer_level",
            field=models.CharField(
                choices=[
                    ("Assisstant", "Assisstant Lecturers"),
                    ("Lecturer 1", "Lecturer 1"),
                    ("Lecturer 2", "Lecturer 2"),
                    ("Lecturer 3", "Lecturer 3"),
                    ("Senior", "Senior Lecturer"),
                    ("Principal", "Principal Lecturer"),
                    ("Chief", "Chief Lecturer"),
                    ("HOD", "Head of Department"),
                ],
                max_length=50,
            ),
        ),
    ]
