# Generated by Django 4.2.5 on 2023-10-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invigilation', '0005_alter_lecturer_lecturer_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='block_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='invigilation_type',
            field=models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('INVIGILATOR', 'Invigilator')], max_length=20),
        ),
    ]
