# Generated by Django 4.2.5 on 2023-10-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invigilation', '0006_hall_block_name_alter_lecturer_invigilation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbe',
            name='exam_supervisor_code',
        ),
        migrations.RemoveField(
            model_name='pbe',
            name='exam_supervisor_code',
        ),
    ]
