# Generated by Django 4.2.5 on 2023-10-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invigilation', '0007_remove_cbe_exam_supervisor_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invigilators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_code', models.CharField(max_length=5)),
                ('exam_hall', models.CharField(max_length=50)),
                ('courses', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('CBE', 'Computer Based Exam'), ('PBE', 'Paper Based Exam')], max_length=5)),
                ('exam_date', models.DateField()),
                ('exam_period', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Afternoon')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_code', models.CharField(max_length=5)),
                ('exam_hall', models.CharField(max_length=50)),
                ('courses', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('CBE', 'Computer Based Exam'), ('PBE', 'Paper Based Exam')], max_length=5)),
                ('exam_date', models.DateField()),
                ('exam_period', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Afternoon')], max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Cbe',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Pbe',
        ),
    ]
