# Generated by Django 4.2.5 on 2023-10-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invigilation', '0008_invigilators_supervisors_delete_cbe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisors',
            old_name='exam_hall',
            new_name='exam_block',
        ),
        migrations.RemoveField(
            model_name='supervisors',
            name='courses',
        ),
        migrations.AlterField(
            model_name='invigilators',
            name='exam_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='supervisors',
            name='exam_date',
            field=models.CharField(max_length=20),
        ),
    ]
