# Generated by Django 4.2.5 on 2023-10-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invigilation', '0009_rename_exam_hall_supervisors_exam_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='block_name',
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('halls', models.ManyToManyField(to='invigilation.hall')),
            ],
        ),
    ]
